# fly.toml app configuration file generated for club-union on 2025-07-24T13:00:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'club-union'
primary_region = 'sin'

[env]
 FLASK_APP = "app.py"

[build]

[http_service]
 internal_port = 8080
 force_https = true
 auto_stop_machines = false
 auto_start_machines = true
 min_machines_running = 1
 processes = ['app']

[[vm]]
 memory = '512mb'
 cpu_kind = 'shared'
 cpus = 1
 memory_mb = 512